# This file was generated by GoReleaser. DO NOT EDIT.
class Hellohomebrew < Formula
  desc "BEW 2.5 - Homebrew Hello World"
  homepage "https://github.com/Abhishek5101/homebrew-hellohomebrew"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Abhishek5101/hellohomebrew/releases/download/v1.0.1/hellohomebrew_1.0.1_macOS-64bit.tar.gz"
    sha256 "0274392f4a718f8566df8187a7de1ae1d6aabb58fc54022540956c421446fb7e"
  elsif OS.linux?
  end

  def install
    bin.install "hellohomebrew"
  end
end
